name: Label Created
on:
  issues:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get label name
      run: echo `${{ github.event.label.name }}`
    # - name: Do something with the label
    #   run: <insert command here>
